[package]
name = "klang"
autotests = true
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
once_cell = "1.17.2"
regex = "1.9.3"
termcolor = "1.2.0"
pest = "2.7.2"
pest_derive = "2.7.2"